### PR TITLE
Fixed custom frame placement

### LINKED ISSUE #51: Fix custom frame placement
### Description:
Now it only works when you place a predefined frame before

### Refinement:
If the issue needs a refinement -> Create new issues and link it as sub-issues in this issue

### PR DESCRIPTION
**Pull request by simonfrayer**
### THE Checklist:
- [x] I have review my code
- [x] I have removed unnecessary comments
- [x] I have merged my **branch** scene into the **main** scene
- [x] I have tested that the app works after merging into the main scene (in Unity is enough)

### CODE REVIEW

File: photo-wall-planner/Assets/photo-wall-planner/scripts/FrameMenuUI.cs [hunk 1]
```diff
@@ -38,21 +43,17 @@ public void OpenOrientationWindow()
         OrientationWindow.SetActive(true);
     }
 
-    
-
-    // Method to set the number of frames in the list
-    private void SetNumberOfFrames()
-    {
-        NumberOfFrames = landScape ? ls_FrameObjects.Count : p_FrameObjects.Count;
-    }
```
Comment (JcullenNZ) [inline photo-wall-planner/Assets/photo-wall-planner/scripts/FrameMenuUI.cs:47]: This doesn't cause an issue with the frame menu?
If not, awesome. I had it set like this in case we would expand the number of frames saved in the frames list - but that's not gonna happen so happy to lose it!

File: photo-wall-planner/Assets/photo-wall-planner/scripts/FramePlacer.cs [hunk 2]
```diff
@@ -12,48 +12,55 @@ public class FramePlacer : PressInputBase
 {
     [SerializeField] private ARRaycastManager raycastManager;
     [SerializeField] private GameObject objectToPlace;
-    [SerializeField] private FrameMenuUI frames;
+    [SerializeField] private FrameMenuUI frameMenuUI;
```
Comment (JcullenNZ) [inline photo-wall-planner/Assets/photo-wall-planner/scripts/FramePlacer.cs:15]: Good catch

File: photo-wall-planner/Assets/photo-wall-planner/scripts/FramePlacer.cs [hunk 3]
```diff
@@ -12,48 +12,55 @@ public class FramePlacer : PressInputBase
...
+        {
+
+            PlaceFrame();
+        }
+
     }
     public void PlaceFrame()
     {
+        Debug.Log("Placing a predefined frame");
+
```
Comment (JcullenNZ) [inline photo-wall-planner/Assets/photo-wall-planner/scripts/FramePlacer.cs:55]: Can probably remove, but not necessary

**Review by JcullenNZ — COMMENTED** [review]
Some surface level comments, but looks good. Nice to realign the naming.

**Review by JcullenNZ — APPROVED** [review]

File: photo-wall-planner/Assets/photo-wall-planner/scripts/FrameMenuUI.cs (hunk 1 above)
Comment (simonfrayer) [reply photo-wall-planner/Assets/photo-wall-planner/scripts/FrameMenuUI.cs:47]: everything working fine when I test
